-- 코드를 입력하세요
SELECT B.AUTHOR_ID AS AUTHOR_ID,A.AUTHOR_NAME,CATEGORY,SUM(PRICE*SALE_CNT) AS TOTAL_SALES
FROM BOOK AS B LEFT JOIN (SELECT *, SUM(SALES) AS SALE_CNT FROM BOOK_SALES AS S WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=01 GROUP BY S.BOOK_ID) AS BGBS ON B.BOOK_ID = BGBS.BOOK_ID LEFT JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC