-- 코드를 입력하세요
SELECT ORDER_ID,PRODUCT_ID,SUBSTRING(OUT_DATE,1,10)AS OUT_DATE, IF(SUBSTRING(OUT_DATE,1,10)<'2022-05-02','출고완료',IF(OUT_DATE is NULL,'출고미정','출고대기')) AS '출고여부'
FROM FOOD_ORDER
ORDER BY ORDER_ID