-- 코드를 작성해주세요
SELECT ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO LEFT JOIN (SELECT PARENT_ITEM_ID
FROM ITEM_TREE
WHERE PARENT_ITEM_ID is NOT NULL) AS C ON ITEM_ID = C.PARENT_ITEM_ID
WHERE PARENT_ITEM_ID is NULL
ORDER BY ITEM_ID DESC