-- 코드를 입력하세요
SELECT SUBSTRING(START_DATE,6,2) AS MONTH,CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE>'2022-07-31' AND START_DATE<'2022-11-01' 
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID)>4 ) AND START_DATE>'2022-07-31' AND START_DATE<'2022-11-01' 
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC
