-- 코드를 입력하세요
SELECT I.REST_ID,I.REST_NAME,I.FOOD_TYPE,FAVORITES,ADDRESS,ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS I JOIN REST_REVIEW AS R ON R.REST_ID = I.REST_ID
WHERE SUBSTRING(ADDRESS,1,2) = '서울'
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC