-- 코드를 입력하세요
SELECT SUBSTRING(SALES_DATE,1,4) AS YEAR, CAST(SUBSTRING(SALES_DATE,6,2) AS UNSIGNED) AS MONTH,GENDER,COUNT(DISTINCT ONLINE_SALE.USER_ID) AS USERS
FROM ONLINE_SALE LEFT JOIN USER_INFO ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
WHERE GENDER is not null
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR,MONTH,GENDER