-- 코드를 입력하세요
SELECT WRITER_ID,NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B 
JOIN USED_GOODS_USER AS F
ON B.WRITER_ID = F.USER_ID
WHERE STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES