-- 코드를 입력하세요
SELECT H.CAR_ID,ROUND(AVG(DATEDIFF(H.END_DATE,H.START_DATE) + 1),1) AS AVERAGE_DURATION FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
GROUP BY H.CAR_ID
HAVING ROUND(AVG(DATEDIFF(H.END_DATE,H.START_DATE)),1)>=6
ORDER BY 2 DESC ,1 DESC