-- 코드를 작성해주세요
SELECT CONCAT(((MONTH(DIFFERENTIATION_DATE)-1) DIV 3 + 1),'Q')as QUARTER, count(*) as ECOLI_COUNT
FROM ECOLI_DATA
group by CONCAT(((MONTH(DIFFERENTIATION_DATE)-1) DIV 3 + 1),'Q')
ORDER BY 1