-- 코드를 입력하세요
SELECT O.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT*PRICE)AS TOTAL_SALES
FROM FOOD_ORDER AS O JOIN FOOD_PRODUCT AS P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE SUBSTRING(PRODUCE_DATE,1,7)='2022-05'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID ASC
