-- 코드를 입력하세요
SELECT HISTORY_ID, (DATEDIFF(END_DATE,START_DATE)+1) * DAILY_FEE * (IF(RATIO IS NOT NULL,RATIO,1)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H JOIN 
(SELECT CAR_ID,DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = '트럭') AS TRUCK ON H.CAR_ID = TRUCK.CAR_ID LEFT JOIN 
(
SELECT SUBSTRING_INDEX(DURATION_TYPE,'일',1) AS DUR,1-SUBSTRING_INDEX(DISCOUNT_RATE,'%',1)/100 AS RATIO
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE CAR_TYPE = '트럭'
)AS DISCOUNT ON IF(DATEDIFF(END_DATE,START_DATE)+1<7,0,IF(DATEDIFF(END_DATE,START_DATE)+1<30,7,IF(DATEDIFF(END_DATE,START_DATE)+1<90,30,90))) = DUR
ORDER BY FEE DESC, HISTORY_ID DESC