-- 코드를 입력하세요
SELECT b.TITLE, b.BOARD_ID,r.REPLY_ID,r.WRITER_ID,r.CONTENTS,DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD as b, USED_GOODS_REPLY as r
WHERE b.CREATED_DATE >'2022-09-30' AND b.CREATED_DATE<'2022-11-01' AND
b.BOARD_ID=r.BOARD_ID
ORDER BY r.CREATED_DATE, b.TITLE