-- 코드를 입력하세요
SELECT F.FLAVOR FROM FIRST_HALF AS F JOIN (SELECT JU.FLAVOR, SUM(JU.TOTAL_ORDER) AS JULY_ORDER FROM JULY AS JU GROUP BY JU.FLAVOR) AS J ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.JULY_ORDER DESC
limit 3