-- 코드를 입력하세요
SELECT ROW_NUM AS HOUR,IF(COUNT is Null,0,COUNT)AS COUNT
FROM
(SELECT @rownum := @rownum+1 AS ROW_NUM
FROM ANIMAL_OUTS,(SELECT @rownum:=-1) AS n
limit 24) AS TIME LEFT JOIN (SELECT CAST(SUBSTRING(DATETIME,12,2) AS UNSIGNED) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM  ANIMAL_OUTS
GROUP BY HOUR
ORDER BY HOUR) AS A ON TIME.ROW_NUM = A.HOUR