-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID, SUBSTRING(START_DATE,1,10) AS START_DATE, SUBSTRING(END_DATE,1,10) AS END_DATE, 
CASE DATEDIFF(END_DATE,START_DATE)+1<30 WHEN TRUE THEN '단기 대여' ELSE '장기 대여' END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE>'2022-08-31' AND START_DATE<'2022-10-01'
ORDER BY HISTORY_ID DESC
