SELECT M.MEMBER_ID, M.MEMBER_NAME, M.GENDER,LEFT(M.DATE_OF_BIRTH,10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE AS M
WHERE IFNULL(M.TLNO,"") != "" AND SUBSTRING(M.DATE_OF_BIRTH,7,1)="3" AND M.GENDER="W"
ORDER BY 1