-- 코드를 작성해주세요
SELECT E.EMP_NO,E.EMP_NAME,G.GRADE, E.SAL DIV 100 * 
(CASE WHEN G.GRADE = 'S' THEN 20 WHEN G.GRADE='A' THEN 15 WHEN G.GRADE='B' THEN 10 ELSE 0 END) AS BONUS
FROM HR_EMPLOYEES AS E JOIN 
(SELECT CASE WHEN AVG(SCORE)>=96 THEN 'S' WHEN AVG(SCORE)>=90 THEN 'A' WHEN AVG(SCORE)>=80 THEN 'B' ELSE 'C' END AS GRADE, EMP_NO
FROM HR_GRADE
GROUP BY EMP_NO)AS G ON (E.EMP_NO = G.EMP_NO)
ORDER BY E.EMP_NO