-- 코드를 입력하세요
SELECT CAST(SUBSTRING(DATETIME,12,2)AS UNSIGNED)AS HOUR,COUNT(ANIMAL_ID)
FROM ANIMAL_OUTS
WHERE CAST(SUBSTRING(DATETIME,12,2)AS UNSIGNED)>8 AND CAST(SUBSTRING(DATETIME,12,2)AS UNSIGNED) < 20
GROUP BY HOUR
ORDER BY HOUR