-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME,I.RARITY
FROM ITEM_INFO AS I RIGHT JOIN(
SELECT T.ITEM_ID
FROM ITEM_INFO AS RI JOIN ITEM_TREE AS T ON RI.ITEM_ID = T.PARENT_ITEM_ID
WHERE RI.RARITY = 'RARE'
)AS UPGRADE_ITEM ON I.ITEM_ID = UPGRADE_ITEM.ITEM_ID
ORDER BY ITEM_ID DESC
