SELECT MONTH(CRH.START_DATE) AS MONTH, CRH.CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRH
JOIN 
(SELECT OVER5.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS OVER5
 WHERE OVER5.START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
 GROUP BY OVER5.CAR_ID HAVING COUNT(OVER5.HISTORY_ID)>4 ) AS O ON CRH.CAR_ID = O.CAR_ID
 WHERE CRH.START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
GROUP BY CRH.CAR_ID,LEFT(CRH.START_DATE,7)
ORDER BY 1, 2 DESC