-- 코드를 작성해주세요
SELECT ID,FISH_NAME,LENGTH
FROM FISH_INFO JOIN (SELECT F.MAX_ID
FROM (SELECT FIRST_VALUE(ID) OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC)AS MAX_ID FROM FISH_INFO) AS F
GROUP BY F.MAX_ID) AS MAXID ON FISH_INFO.ID = MAXID.MAX_ID NATURAL JOIN FISH_NAME_INFO