-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS R
ON C.CAR_ID = R.CAR_ID
WHERE CAR_TYPE = '세단' AND (START_DATE<'2022-11-01' AND START_DATE>'2022-09-30')
GROUP BY CAR_ID
ORDER BY CAR_ID DESC