SELECT F.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F JOIN (SELECT *, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('식용유','과자','국','김치')
GROUP BY CATEGORY) AS M ON (F.CATEGORY = M.CATEGORY && M.MAX_PRICE = F.PRICE) 
ORDER BY MAX_PRICE DESC
