-- 코드를 작성해주세요
SELECT GRADE,ID,EMAIL
FROM 
(SELECT IF(FRONT.isFront=True,IF(PYTHON.isPython=True,'A',IF(CSHARP.isCsharp=True,'B','C')),IF(CSHARP.isCsharp=True,'B',Null)) AS GRADE, D.ID,D.EMAIL
FROM DEVELOPERS AS D LEFT JOIN 
(SELECT D.ID, True AS 'IsFront'
FROM DEVELOPERS AS D JOIN SKILLCODES AS C ON D.SKILL_CODE DIV C.CODE MOD 2 =1
WHERE C.NAME  in (SELECT NAME
FROM SKILLCODES
WHERE CATEGORY = 'Front End')
GROUP BY D.ID) AS FRONT ON D.ID = FRONT.ID
LEFT JOIN (SELECT ID, True AS 'isCsharp'
FROM DEVELOPERS
WHERE SKILL_CODE DIV (SELECT CODE FROM SKILLCODES WHERE NAME='C#') mod 2 =1) AS CSHARP
ON D.ID = CSHARP.ID
LEFT JOIN (SELECT ID, True AS 'isPython'
FROM DEVELOPERS
WHERE SKILL_CODE DIV (SELECT CODE FROM SKILLCODES WHERE NAME='Python') mod 2 =1) AS PYTHON
ON D.ID = PYTHON.ID
) AS RESULT
WHERE GRADE is not null
ORDER BY GRADE, ID